---
- hosts: all
  become: true
  gather_facts: yes

  pre_tasks:

  roles:
    - role: common
    - role: database
      when: db is defined
    - role: app
      when: app is defined
    - role: web
      when: web is defined

  post_tasks:

